name: push to zenn
on:
  push:
    branches: [master]
    paths:
    - 'ja/**'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - id: generate_token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        repositories: zenn.dev
    - uses: Songmu/action-push-to-another-repository@9a7fe32305f083e5e0984e345f30940d0ff87706 # v2.0.11
      with:
        token: ${{ steps.generate_token.outputs.token }}
        source-directory: ja
        destination-repository: Songmu/zenn.dev
        destination-directory: books/ghq-handbook
