name: push to zenn
on:
  push:
    branches: [master]
    paths:
    - 'ja/**'
permissions:
  contents: read
jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - id: generate_token
      uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        repositories: zenn.dev
        permission-contents: write
    - uses: Songmu/action-push-to-another-repository@9a7fe32305f083e5e0984e345f30940d0ff87706 # v2.0.11
      with:
        token: ${{ steps.generate_token.outputs.token }}
        source-directory: ja
        destination-repository: Songmu/zenn.dev
        destination-directory: books/ghq-handbook
